### PR TITLE
OTP24 compatibility

### PR DESCRIPTION
**Pull request by mworrell**
Also adds:

 - Github Actions
 - xref check command
 
For the GH Action to publish to Hex we need to add a Hex API key.

### CODE REVIEW

**Comment by mworrell** [comment]
@mmzeeman In OTP24 the old crypto API has been removed.  But it seems that the cipher we are using is not available in the new API on OTP22/23.

Shall we add a test to use the old functions on OTP22/23?

**Comment by mmzeeman** [comment]
The cipher was chosen in such a way that it was also available in web clients. Interesting.

**Comment by mworrell** [comment]
Looks like an omission in the new crypto functions, now using the old _block_ functions on OTP22/23.

**Review by mmzeeman — COMMENTED** [review]
Looks good to me..

**Comment by mworrell** [comment]
Then I'll merge

**Pull request merged**
